---
name: linter
# This workflow is triggered on pushes to the repository.
on:
  push:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  terraform-validate:
    name: code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v3.0.0

      - name: Cache terraform folder
        uses: actions/cache@v4.0.2
        with:
          path: ./.terraform
          key: terraform

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

      - name: terraform init
        run: |
          terraform version
          terraform init

      - name: terraform validate
        run: terraform validate
